import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StyledComponentsRegistry from "./ui/preloadcss";
import { Layout } from "antd";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Nursary",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-200">
                  <StyledComponentsRegistry>
                  <Layout style={{ minHeight: '100vh' ,flexDirection: "initial" }}>
                    {children}
                  </Layout>
                  </StyledComponentsRegistry>
      </body>
    </html>
  );
}
