// import React from "react";
// import { Table } from "antd";

// const columns = [
//   {
//     title: "令和４年度",
//     dataIndex: "ageGroup",
//     key: "ageGroup",
//     width: "180px",
//   },
//   {
//     title: "実績",
//     children: [
//       { title: "4月", dataIndex: "apr", key: "apr" },
//       { title: "5月", dataIndex: "may", key: "may" },
//       { title: "6月", dataIndex: "jun", key: "jun" },
//       { title: "7月", dataIndex: "jul", key: "jul" },
//       { title: "8月", dataIndex: "aug", key: "aug" },
//       { title: "9月", dataIndex: "sep", key: "sep" },
//       { title: "10月", dataIndex: "oct", key: "oct" },
//       { title: "11月", dataIndex: "nov", key: "nov" },
//       { title: "12月", dataIndex: "dec", key: "dec" },
//       { title: "1月", dataIndex: "jan", key: "jan" },
//       { title: "2月", dataIndex: "feb", key: "feb" },
//       { title: "3月", dataIndex: "mar", key: "mar" },
//     ],
//   },
//   {
//     title: "平均児童数",
//     dataIndex: "average",
//     key: "average",
//   },
// ];

// const data = [
//   {
//     key: "1",
//     ageGroup: "４歳以上児",
//     children: [
//       {
//         key: "1-1",
//         type: "児童数",
//         apr: "18人",
//         may: "18人",
//         jun: "18人",
//         jul: "18人",
//         aug: "18人",
//         sep: "18人",
//         oct: "18人",
//         nov: "18人",
//         dec: "18人",
//         jan: "18人",
//         feb: "18人",
//         mar: "18人",
//       },
//       {
//         key: "1-2",
//         type: "伸び率",
//         apr: "1.00",
//         may: "1.00",
//         jun: "1.00",
//         jul: "1.00",
//         aug: "1.00",
//         sep: "1.00",
//         oct: "1.00",
//         nov: "1.00",
//         dec: "1.00",
//         jan: "1.00",
//         feb: "1.00",
//         mar: "1.00",
//       },
//     ],
//   },
//   {
//     key: "2",
//     ageGroup: "３歳児",
//     children: [
//       {
//         key: "2-1",
//         type: "児童数",
//         apr: "18人",
//         may: "18人",
//         jun: "18人",
//         jul: "18人",
//         aug: "18人",
//         sep: "18人",
//         oct: "18人",
//         nov: "18人",
//         dec: "18人",
//         jan: "18人",
//         feb: "18人",
//         mar: "18人",
//       },
//       {
//         key: "2-2",
//         type: "伸び率",
//         apr: "1.00",
//         may: "1.00",
//         jun: "1.00",
//         jul: "1.00",
//         aug: "1.00",
//         sep: "1.00",
//         oct: "1.00",
//         nov: "1.00",
//         dec: "1.00",
//         jan: "1.00",
//         feb: "1.00",
//         mar: "1.00",
//       },
//     ],
//   },
//   {
//     key: "3",
//     ageGroup: "うち満３歳児（認定こども園のみ）",
//     children: [
//       {
//         key: "3-1",
//         type: "児童数",
//         apr: "0人",
//         may: "0人",
//         jun: "0人",
//         jul: "0人",
//         aug: "0人",
//         sep: "0人",
//         oct: "0人",
//         nov: "0人",
//         dec: "0人",
//         jan: "0人",
//         feb: "0人",
//         mar: "0人",
//       },
//       {
//         key: "3-2",
//         type: "伸び率",
//         apr: "",
//         may: "",
//         jun: "",
//         jul: "",
//         aug: "",
//         sep: "",
//         oct: "",
//         nov: "",
//         dec: "",
//         jan: "",
//         feb: "",
//         mar: "",
//       },
//     ],
//   },
//   {
//     key: "4",
//     ageGroup: "１、２歳児",
//     children: [
//       {
//         key: "4-1",
//         type: "児童数",
//         apr: "30人",
//         may: "30人",
//         jun: "30人",
//         jul: "30人",
//         aug: "30人",
//         sep: "30人",
//         oct: "30人",
//         nov: "30人",
//         dec: "30人",
//         jan: "30人",
//         feb: "30人",
//         mar: "30人",
//       },
//       {
//         key: "4-2",
//         type: "伸び率",
//         apr: "1.00",
//         may: "1.00",
//         jun: "1.00",
//         jul: "1.00",
//         aug: "1.00",
//         sep: "1.00",
//         oct: "1.00",
//         nov: "1.00",
//         dec: "1.00",
//         jan: "1.00",
//         feb: "1.00",
//         mar: "1.00",
//       },
//     ],
//   },
//   {
//     key: "5",
//     ageGroup: "０歳児",
//     children: [
//       {
//         key: "5-1",
//         type: "児童数",
//         apr: "6人",
//         may: "6人",
//         jun: "7人",
//         jul: "7人",
//         aug: "7人",
//         sep: "7人",
//         oct: "7人",
//         nov: "7人",
//         dec: "7人",
//         jan: "7人",
//         feb: "7人",
//         mar: "7人",
//       },
//       {
//         key: "5-2",
//         type: "伸び率",
//         apr: "1.00",
//         may: "1.17",
//         jun: "1.17",
//         jul: "1.17",
//         aug: "1.17",
//         sep: "1.17",
//         oct: "1.17",
//         nov: "1.17",
//         dec: "1.17",
//         jan: "1.17",
//         feb: "1.17",
//         mar: "1.17",
//       },
//     ],
//   },
//   {
//     key: "6",
//     ageGroup: "合計",
//     children: [
//       {
//         key: "6-1",
//         type: "児童数",
//         apr: "",
//         may: "",
//         jun: "",
//         jul: "",
//         aug: "",
//         sep: "",
//         oct: "",
//         nov: "",
//         dec: "",
//         jan: "",
//         feb: "",
//         mar: "",
//       },
//       {
//         key: "6-2",
//         type: "平均児数",
//         apr: "",
//         may: "",
//         jun: "",
//         jul: "",
//         aug: "",
//         sep: "",
//         oct: "",
//         nov: "",
//         dec: "",
//         jan: "",
//         feb: "",
//         mar: "73人",
//       },
//     ],
//   },
// ];

// const AgeAverageCalculator = ({ data }: { data: Array<object> }) => {
//   return <Table columns={columns} dataSource={data} bordered />;
// };

// export default AgeAverageCalculator;

import React from "react";
import { Table } from "antd";

const columns = [
  {
    title: "令和４年度",
    dataIndex: "ageGroup",
    key: "ageGroup",
    width: "180px",
  },
  {
    title: "実績",
    children: [
      { title: "4月", dataIndex: "apr", key: "apr" },
      { title: "5月", dataIndex: "may", key: "may" },
      { title: "6月", dataIndex: "jun", key: "jun" },
      { title: "7月", dataIndex: "jul", key: "jul" },
      { title: "8月", dataIndex: "aug", key: "aug" },
      { title: "9月", dataIndex: "sep", key: "sep" },
      { title: "10月", dataIndex: "oct", key: "oct" },
      { title: "11月", dataIndex: "nov", key: "nov" },
      { title: "12月", dataIndex: "dec", key: "dec" },
      { title: "1月", dataIndex: "jan", key: "jan" },
      { title: "2月", dataIndex: "feb", key: "feb" },
      { title: "3月", dataIndex: "mar", key: "mar" },
    ],
  },
  {
    title: "平均児童数",
    dataIndex: "average",
    key: "average",
  },
];

const data = [
  {
    key: "1",
    ageGroup: "４歳以上児",
    children: [
      {
        key: "1-1",
        type: "児童数",
        apr: "18人",
        may: "18人",
        jun: "18人",
        jul: "18人",
        aug: "18人",
        sep: "18人",
        oct: "18人",
        nov: "18人",
        dec: "18人",
        jan: "18人",
        feb: "18人",
        mar: "18人",
      },
      {
        key: "1-2",
        type: "伸び率",
        apr: "1.00",
        may: "1.00",
        jun: "1.00",
        jul: "1.00",
        aug: "1.00",
        sep: "1.00",
        oct: "1.00",
        nov: "1.00",
        dec: "1.00",
        jan: "1.00",
        feb: "1.00",
        mar: "1.00",
      },
    ],
  },
  {
    key: "2",
    ageGroup: "３歳児",
    children: [
      {
        key: "2-1",
        type: "児童数",
        apr: "18人",
        may: "18人",
        jun: "18人",
        jul: "18人",
        aug: "18人",
        sep: "18人",
        oct: "18人",
        nov: "18人",
        dec: "18人",
        jan: "18人",
        feb: "18人",
        mar: "18人",
      },
      {
        key: "2-2",
        type: "伸び率",
        apr: "1.00",
        may: "1.00",
        jun: "1.00",
        jul: "1.00",
        aug: "1.00",
        sep: "1.00",
        oct: "1.00",
        nov: "1.00",
        dec: "1.00",
        jan: "1.00",
        feb: "1.00",
        mar: "1.00",
      },
    ],
  },
  {
    key: "3",
    ageGroup: "うち満３歳児（認定こども園のみ）",
    children: [
      {
        key: "3-1",
        type: "児童数",
        apr: "0人",
        may: "0人",
        jun: "0人",
        jul: "0人",
        aug: "0人",
        sep: "0人",
        oct: "0人",
        nov: "0人",
        dec: "0人",
        jan: "0人",
        feb: "0人",
        mar: "0人",
      },
      {
        key: "3-2",
        type: "伸び率",
        apr: "",
        may: "",
        jun: "",
        jul: "",
        aug: "",
        sep: "",
        oct: "",
        nov: "",
        dec: "",
        jan: "",
        feb: "",
        mar: "",
      },
    ],
  },
  {
    key: "4",
    ageGroup: "１、２歳児",
    children: [
      {
        key: "4-1",
        type: "児童数",
        apr: "30人",
        may: "30人",
        jun: "30人",
        jul: "30人",
        aug: "30人",
        sep: "30人",
        oct: "30人",
        nov: "30人",
        dec: "30人",
        jan: "30人",
        feb: "30人",
        mar: "30人",
      },
      {
        key: "4-2",
        type: "伸び率",
        apr: "1.00",
        may: "1.00",
        jun: "1.00",
        jul: "1.00",
        aug: "1.00",
        sep: "1.00",
        oct: "1.00",
        nov: "1.00",
        dec: "1.00",
        jan: "1.00",
        feb: "1.00",
        mar: "1.00",
      },
    ],
  },
  {
    key: "5",
    ageGroup: "０歳児",
    children: [
      {
        key: "5-1",
        type: "児童数",
        apr: "6人",
        may: "6人",
        jun: "7人",
        jul: "7人",
        aug: "7人",
        sep: "7人",
        oct: "7人",
        nov: "7人",
        dec: "7人",
        jan: "7人",
        feb: "7人",
        mar: "7人",
      },
      {
        key: "5-2",
        type: "伸び率",
        apr: "1.00",
        may: "1.17",
        jun: "1.17",
        jul: "1.17",
        aug: "1.17",
        sep: "1.17",
        oct: "1.17",
        nov: "1.17",
        dec: "1.17",
        jan: "1.17",
        feb: "1.17",
        mar: "1.17",
      },
    ],
  },
  {
    key: "6",
    ageGroup: "合計",
    children: [
      {
        key: "6-1",
        type: "児童数",
        apr: "",
        may: "",
        jun: "",
        jul: "",
        aug: "",
        sep: "",
        oct: "",
        nov: "",
        dec: "",
        jan: "",
        feb: "",
        mar: "",
      },
      {
        key: "6-2",
        type: "平均児数",
        apr: "",
        may: "",
        jun: "",
        jul: "",
        aug: "",
        sep: "",
        oct: "",
        nov: "",
        dec: "",
        jan: "",
        feb: "",
        mar: "73人",
      },
    ],
  },
];

const flattenData = (data: any[]) => {
  return data.reduce((result, item) => {
    const { ageGroup, children } = item;
    const row: { [key: string]: any } = { ageGroup };
    children.forEach((child: { type: string | number; apr: any }) => {
      row[child.type as string] = child.apr;
    });
    row.average = children[children.length - 1].mar;
    result.push(row);
    return result;
  }, []);
};

const AgeAverageCalculator = ({ data }: { data: any[] }) => {
  const flattenedData = flattenData(data);
  return <Table columns={columns} dataSource={flattenedData} bordered />;
};

export default AgeAverageCalculator;
